server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobAuthdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "P9edfc7xqRlU9zmlA3/Iy1/BkVjasyS+V4sTU2ERk8M="
  expiration: 86400000 # 1 day

eureka:
  preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

