server:
  port: 8085

spring:
  application:
    name: application-service

  datasource:
    url: jdbc:postgresql://localhost:5432/jobapplicationdb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

jwt:
  secret: "P9edfc7xqRlU9zmlA3/Iy1/BkVjasyS+V4sTU2ERk8M="
  expiration: 86400000 # 1 day
