apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-db
  namespace: job-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-db
  template:
    metadata:
      labels:
        app: application-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: job_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: application-db
  namespace: job-portal
spec:
  selector:
    app: application-db
  ports:
    - port: 5432