apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: job-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job
          image: thilinarodrigo/job-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://job-db:5432/job_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8070/eureka/

---

apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: job-portal
spec:
  selector:
    app: job-service
  ports:
    - port: 80
      targetPort: 8082