server:
  port: 8083

spring:
  application:
    name: employer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/employerdb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

